name: Push to Wikipedia

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Push to Wikipedia
        env:
          ENWIKI_USER: ${{secrets.USER}}
          ENWIKI_PASS: ${{secrets.PASS}}
        run: python enwiki.py
